### ISSUE TITLE
Newer releases are not being published to NPM

### ISSUE THREAD

**Issue by FoxxMD** [LukeHagar/plexjs#26]
Releases newer than 0.23.5 are not being [published to NPM](https://www.npmjs.com/package/@lukehagar/plexjs?activeTab=versions) even though the releases have a link to an [npm version in the release details.](https://github.com/LukeHagar/plexjs/releases/tag/v0.26.1).

**Comment by JasonLandbridge** [comment]
@LukeHagar I tried manually kicking off the publish flow but I don't have sufficient rights: https://github.com/LukeHagar/plexjs/actions/runs/11481610663/job/31952702087

**Comment by LukeHagar** [comment]
I'll get it sorted. Thanks for the heads up

**Comment by evandcoleman** [comment]
Any updates on this?

**Comment by LukeHagar** [comment]
Hey Evan,

It’s an issue with the generator package we use, I don’t have any updates
yet nor an ETA

**Comment by FoxxMD** [comment]
Please address this...this package is greate and one of the only decent TS libraries for plex usage but not having any new packages, from what should be autogenerated typings, for 3 months and the idea of no bugs being to be fixed due to this is making me considering refactoring away from this library or forking under a private scope. I'd prefer to not have to do this.

**Comment by JasonLandbridge** [comment]
@FoxxMD Looking at it again, I think I figured out the issue and will fix it as we speak

**Comment by LukeHagar** [comment]
This is definitely still an issue, @JasonLandbridge lets restore those parameters on the endpoints please.

I have an open ticket for this issue internally, I will follow up with them this week and see if I can get it prioritized.

It is some kind of edge case that is causing the imports to be specified twice, absolutely an issue, but I'm not clear on how its being triggered.

The `x-speakeasy-global` extension is intended to allow for global instantiation of common parameters, but seems to be malfunctioning here.

**Comment by JasonLandbridge** [comment]
> This is definitely still an issue, @JasonLandbridge lets restore those parameters on the endpoints please.

But these are duplicate parameters, they are already defined globally in `x-speakeasy-global` so they're redundant right when also defined on the endpoint level?

> I have an open ticket for this issue internally, I will follow up with them this week and see if I can get it prioritized.

The fact that this is taking so long within the company should not be made an issue for users. Then I would rather have an updated workable build now, fix the SDK generation and then put the parameters back. Then that would minimize the downtime for projects dependent on this and will give Speakeasy the time they need.

> It is some kind of edge case that is causing the imports to be specified twice, absolutely an issue, but I'm not clear on how its being triggered.

Just a shot in the dark here, but aren't they defined twice and therefore generated twice? The SDK generation could filter for duplicate headers and that could solve it.

**Comment by LukeHagar** [comment]
> But these are duplicate parameters, they are already defined globally in x-speakeasy-global so they're redundant right when also defined on the endpoint level?

The `x-speakeasy-global` parameter is just intended to allow a specific set of parameters to be specified globally, and then be imported FROM the global scope ONLY when the parameter is BOTH in the globals extension and specified individually on the endpoint, but that specific functionality seems to be the part malfunctioning here.

So this is a bit of a catch-22 due to the bug, as the best solution I see is to remove the globals extension, but then anyone who was specifying those parameters globally, such as the usage example for every method indicate, would need to migrate those values to being specified at the method level.

If you have ideas on the best way to get this addressed I'm open to discussion, but I believe fixing it in the tool will be best. I'm getting a minimum reproduction made today to get this resolved.

**Comment by JasonLandbridge** [comment]
> The `x-speakeasy-global` parameter is just intended to allow a specific set of parameters to be specified globally, and then be imported FROM the global scope ONLY when the parameter is BOTH in the globals extension and specified individually on the endpoint, but that specific functionality seems to be the part malfunctioning here.

Ah, did not know both were needed. Yeah, then it needs to be reverted

> So this is a bit of a catch-22 due to the bug, as the best solution I see is to remove the globals extension, but then anyone who was specifying those parameters globally, such as the usage example for every method indicate, would need to migrate those values to being specified at the method level.

Luckily, the parameters are generic Plex analytics tracker parameters, so I can't think of a use case for users using them anyway. It was added mostly to be technically complete.

> If you have ideas on the best way to get this addressed I'm open to discussion, but I believe fixing it in the tool will be best. I'm getting a minimum reproduction made today to get this resolved.

Yeah, the tool fix would be best, but it's honestly taking too long, so I'm more in favor of any workaround. So then I would argue for temporarily removing the `x-speakeasy-global` parameter.

**Comment by JasonLandbridge** [comment]
Cool, I will make a quick PR

**Comment by LukeHagar** [comment]
I believe a new version was successfully released

**Comment by FoxxMD** [comment]
Hurrah! Thank you both for getting this solved! :heart:

**Comment by JasonLandbridge** [comment]
Happy to help! :smile:

**Comment by LukeHagar** [comment]
Thank YOU for your patience. :)
