### ISSUE TITLE
Any chance of a new NPM release?

### ISSUE THREAD

**Issue by conroy-cheers** [LukeHagar/plexjs#3]
First of all, thanks for making this - it's (mostly) sane to use in a TS project and covers all the APIs I wanted to use, unlike a couple of other Plex API packages I tried.

Any chance of a 0.0.28 release to NPM? There are a bunch of new endpoints supported on main that don't exist on 0.0.27, and installing straight from the GitHub repo isn't quite straightforward.
Would it make sense to have a workflow automatically version bump and/or publish to NPM when the upstream API definitions are pulled in?

**Comment by LukeHagar** [comment]
Hey Conroy!

I’m glad you like it, I’m happy to release more versions of it, I have a
flow that makes it easy enough. In my experience with code generation from
specs there can be lots of unforeseen issues, so I’m inclined to keep it
manual for now.

That being said I’m certainly open to talking about it further, what do you
think would be the best course of action?

**Comment by conroy-cheers** [comment]
You're right, it could be risky to automatically push releases without any testing...
Ideally, I think a workflow may look something like:

1. When upstream API spec is updated, trigger the workflow
2. Regenerate TS library from upstream changes
3. Run some automated tests on the newly generated code - this would probably be a lot of work, could look something like
a) Spin up a Plex instance in a container
b) Add some example user accounts / media / playlists / whatever else you need for testing using a script
c) Above two points aren't really specific to this library so could be done in another repo. Maybe I'll have a look into it
d) Run automated tests against the predefined Plex instance / data
4. At this point, if the tests pass, the generated code is (probably) ok, so commit it to main
5. Trigger a deployment with [manual approval](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments). Deployment should:
a) Bump version number and commit to main
b) Create a new git tag with the version number, pointing to the version bump commit it just made
c) Do final packaging and push to npm

(This is all off the top of my head, so some steps might be a bit wrong)
Actually, this might be an improvement even without the automated tests step; could get started now and add those later.
Also, I noticed the TS library generation is currently done by an action on the plex-api-spec repo - up to you, but the spec can exist without the library, but not the other way around, so IMO it's better to move this generation action to the library repo.
Also noticed a lot of build fails on the API spec repo; I think it might be better to keep quick-and-dirty changes on a develop branch and merge them into main when you think they're good (and/or they're validated by the openapi tools). This way the main branch can be trusted as probably-ok by the new actions on this repo, so we're not triggering a zillion unnecessary workflow runs.

What do you think? Feel free to suggest any changes.
If you don't hate it and want to give it a shot I'm happy to help out :) If you don't have enough time then I'd be willing to give it a try and make a PR.

**Comment by LukeHagar** [comment]
I have a lot going on in my day job currently so I won't be able to really take a crack at this for a while, but I welcome any PRs or improvements to this project or to the API specs that this is built from.

**Comment by LukeHagar** [comment]
@conroy-cheers, I'm using a new tool that should regenerate the SDK every day that the Spec has changed, so if you want to update the spec, those changes will be reflected in the SDK at least the next day.
